module RunfileTasks
  module Testing
    extend self

    def cucumber
      usage  "(feature|features) [<tag_or_file> --list]"
      help   "Run cucumber feature tests. Optionally, specify a tag or a filename to run. Tags should be prefixed with @."
      option "--list", "Show list of available features"
      action :feature, :features do |args|
        if args['--list']
          show_cucumber_features
        else
          run_cucumber_features args['<tag_or_file>']
        end
      end
    end

    def cucumber_stepdefs(filename='stepdefs.md')
      usage  "stepdefs"
      help   "Generate step definitions markdown document.\n" +
             "Comments in the step definition file that start with two or " +
             "more # characters, will also be added to the output " +
             "document, as captions."
      action :stepdefs do
        step = /^(Given|When|Then)\((\/.*\/)\) do.*$/
        caption = /^(\#{2,6} .*)$/
        files = Dir['features/step_definitions/**/*.rb']
        doc = []
        doc << "# Cucumber Step Definitions Summary\n"
        doc << "Generated by `run stepdefs`."
        files.each do |file|
          doc << "\n## #{File.basename(file, '.rb')}\n"
          File.readlines(file).each do |line|
            if matches = step.match(line)
              clause = matches.captures[0]
              definition = matches.captures[1] # .gsub /(".*?")/, '`__\1__`'
              doc << "- __`#{clause}`__ `#{definition}`"
            end
            if matches = caption.match(line)
              title = matches.captures[0]
              doc << "\n#{title}\n"
            end
          end
        end
        doc = doc.join "\n"
        File.write filename, doc
        say "Generated #{filename}"  
      end
    end

    def show_cucumber_features
      say "!txtgrn!Available Features:"
      Dir['features/**/*.feature'].each do |file|
        say "- " + File.basename("#{file}", '.feature')
      end
    end

    def run_cucumber_features(tag_or_file)
      cmd = "cucumber"
      if tag_or_file
        if tag_or_file[0] == '@' 
          say "!txtgrn!Running features tagged #{tag_or_file}"
          cmd = "#{cmd} --tags #{tag_or_file}"
        else
          say "!txtgrn!Running #{tag_or_file} features"
          cmd = "#{cmd} 'features/#{tag_or_file}.feature'"
        end
      end
      exec cmd
    end

  end
end
